apiVersion: v1
kind: Pod
metadata:
  name: train-pod
spec:
  restartPolicy: Never
  containers:
  - name: train
    image: mm12063/mnist_train:2.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
    volumeMounts:
      - name: app-pv
        mountPath: /home/app
  volumes:
    - name: app-pv
      persistentVolumeClaim:
        claimName: model-holder